// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxS6v-L494TKA1opz2O0EyoQGpcmYMIJw',
    appId: '1:891261041543:web:255a021d952bc8c706b122',
    messagingSenderId: '891261041543',
    projectId: 'test-kasir',
    authDomain: 'test-kasir.firebaseapp.com',
    storageBucket: 'test-kasir.appspot.com',
    measurementId: 'G-P5NHS5E1EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW_xWcfBxJ4kfoztZ4JUmdmkRvlBWnhEk',
    appId: '1:891261041543:android:7ea73fc63c4515ab06b122',
    messagingSenderId: '891261041543',
    projectId: 'test-kasir',
    storageBucket: 'test-kasir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtWzE9DekNcySwwPEGj6NypEThhpT3k0Q',
    appId: '1:891261041543:ios:8ac6b1503a8fb3dd06b122',
    messagingSenderId: '891261041543',
    projectId: 'test-kasir',
    storageBucket: 'test-kasir.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtWzE9DekNcySwwPEGj6NypEThhpT3k0Q',
    appId: '1:891261041543:ios:8ac6b1503a8fb3dd06b122',
    messagingSenderId: '891261041543',
    projectId: 'test-kasir',
    storageBucket: 'test-kasir.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxS6v-L494TKA1opz2O0EyoQGpcmYMIJw',
    appId: '1:891261041543:web:a9a6e39b08aab11606b122',
    messagingSenderId: '891261041543',
    projectId: 'test-kasir',
    authDomain: 'test-kasir.firebaseapp.com',
    storageBucket: 'test-kasir.appspot.com',
    measurementId: 'G-RH2HKKJXF7',
  );

}